### PR TITLE
Filet Mignon: Adding Key for blacksausage

### PR DESCRIPTION
**Pull request by blacksausage**
Yes we can!

### CODE REVIEW

**Comment by jkrauska** [comment]
@blacksausage  looks like you need to rebase from master.

This isn't a clean merge.

**Comment by jkrauska** [comment]
@blacksausage  it's still showing 3 file edits that shouldn't be in there.

I'd try a clean start off master.

**Comment by jkrauska** [comment]
@blacksausage lets make this easy -- send me your key in this thread or on Discord.

**Comment by blacksausage** [comment]
tNci7iuDyJDhv6ZYZLJbHjgEaU5h3s3nsKvJppxibw64St1nhXcjaJAvWmK4WPKHEKtqQiPw5giXsrimmfFDqaFuysWe8MXsNCsvdwb4bTQZQrCnNogjQGwZk7v9zxdcjUgQ5XPp8fUruj

**Comment by blacksausage** [comment]
Key

**Comment by jkrauska** [comment]
Applied in #190  -- Happy Staking!

**Pull request closed without merging**
