### PR TITLE
Staking Challenge: Adding Key for Marius | Ubik Capital#9009

### PR DESCRIPTION
**Pull request by UbikCapital**
Staking Challenge: Adding Key for Marius | Ubik Capital#9009

### CODE REVIEW

**Comment by bkase** [comment]
Looks like this is the old style of public key

**Comment by UbikCapital** [comment]
> Looks like this is the old style of public key
Please look at Staking Challenge: Adding Key for Marius | Ubik Capital#9009  key. 
489a308
There you can find new key.

**Comment by UbikCapital** [comment]
> Looks like this is the old style of public key

Thanks. I think that now is ok.

**Comment by bkase** [comment]
this branch is messed up I'll add this line in a separate PR

tdNDftGmTyYSThU3vsgXUAKQsREjopAj5MyeheBoYK8QrSgkcx93qjwo4Nt72N9UEjz3p5ye1zRVdQBbbVc853rpQHgaGN6L6oRSodY5veGmpwKaJSBXvzzDVuD2MGWKVeBJgXqpcK8RUz

**Comment by UbikCapital** [comment]
Thanks!

**Pull request closed without merging**
